# Generated by Django 4.2 on 2023-07-13 02:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="program",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fernet_key",
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.DateField(default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gallery",
            field=models.ImageField(
                blank=True,
                height_field="24",
                null=True,
                upload_to="gallery/",
                width_field="30",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="university_name",
            field=models.CharField(
                choices=[
                    ("ucc", "University of Cape Coast"),
                    ("ug", "University of Ghana"),
                    ("knust", "Kwame Nkrumah University of Science and Technology"),
                    ("uew", "University of Education, Winneba"),
                    ("umat", "University of Mines and Technology"),
                    ("uds", "University of Development Studies"),
                    ("upsa", "University of Professional Studies, Accra"),
                    ("uenr", "University of Energy and Natural Resources"),
                    ("uhas", "University of Health and Allied Sciences"),
                    (
                        "gimpa",
                        "Ghana Institute of Management and Public Administration",
                    ),
                    ("atu", "Accra Technical University"),
                    ("ashesi", "Ashesi University"),
                    ("central", "Central University"),
                    ("kstu", "Kumasi Technical University"),
                ],
                max_length=255,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
