# Generated by Django 4.2 on 2023-07-13 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_userprofile_program_userprofile_fernet_key_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="university_name",
            new_name="university",
        ),
    ]
