# Generated by Django 4.2 on 2023-07-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_rename_university_name_userprofile_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="university",
            field=models.CharField(
                choices=[
                    ("ucc", "University of Cape Coast"),
                    ("ug", "University of Ghana"),
                    ("knust", "Kwame Nkrumah University of Science and Technology"),
                    ("uew", "University of Education, Winneba"),
                    ("umat", "University of Mines and Technology"),
                    ("uds", "University of Development Studies"),
                    ("upsa", "University of Professional Studies, Accra"),
                    ("uenr", "University of Energy and Natural Resources"),
                    ("uhas", "University of Health and Allied Sciences"),
                    (
                        "gimpa",
                        "Ghana Institute of Management and Public Administration",
                    ),
                    ("atu", "Accra Technical University"),
                    ("ashesi", "Ashesi University"),
                    ("central", "Central University"),
                    ("kstu", "Kumasi Technical University"),
                ],
                max_length=255,
            ),
        ),
    ]
