# Generated by Django 4.2 on 2023-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_userprofile_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
    ]
