# Generated by Django 4.2.2 on 2023-07-20 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_userprofile_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="age",
        ),
    ]
